### ISSUE TITLE
Uncaught CKEditorError: ckeditor-duplicated-modules: Some CKEditor 5 modules are duplicated

### ISSUE THREAD

**Issue by umitkirtil** [eroself/vaadin-litelement-ckeditor#1]
Hi Great wrapper but i faced this error both debug and production mode.

Error directs to this link : https://ckeditor.com/docs/ckeditor5/latest/framework/guides/support/error-codes.html#error-ckeditor-duplicated-modules

![image](https://user-images.githubusercontent.com/19428163/78169350-e8828280-7459-11ea-81df-b971ceba7604.png)

**Comment by eroself** [comment]
Thanks for giving it a go.
New version released to fix this issue.

**Comment by umitkirtil** [comment]
1.0.1 solves issue ... thanks a lot.
