### ISSUE TITLE
CKEDITOR.ClassicEditor is null

### ISSUE THREAD

**Issue by mheicke** [eroself/vaadin-litelement-ckeditor#10]
Version: 1.0.5
Vaadin Version: 14.3.2

I added vaadin-litelement-ckeditor to our project but when the class is loaded, there's a _undefined_ exception in
`createEditor() {
        this.getEditorByType(this.editorType).create(document.querySelector( "#"+this.editorId ) ,...`
looking deeper into it it's because CKEDITOR.ClassicEditor (as well as CKEDITOR.InlineEditor, CKEDITOR.BalloonEditor etc) are null.

Maven clean, removing and rebuilding the npm files etc did not help.

<img width="1440" alt="Bildschirmfoto 2020-08-10 um 19 31 56" src="https://user-images.githubusercontent.com/246571/89812301-31e98980-db40-11ea-8efd-aaeab3aae23b.png">

**Comment by eroself** [comment]
What is your `this.editorType`?

**Comment by mheicke** [comment]
"classic", so it's returning the content of CKEDITOR.ClassicEditor, but this is somehow undefined (as well as all the others like CKEDITOR.InlineEditor).
<img width="1440" alt="Bildschirmfoto 2020-08-11 um 00 14 32" src="https://user-images.githubusercontent.com/246571/89836728-aab00c00-db67-11ea-9122-938e317aadc3.png">

**Comment by eroself** [comment]
![image](https://user-images.githubusercontent.com/3937758/89839160-35712500-dbc1-11ea-8514-9ecba9951cf6.png)
Normally, `this.getEditorByType(this.editorType)` will return a class depending on the editorType.
CKEDITOR is for [production mode](https://vaadin.com/docs/flow/production/tutorial-production-mode-basic.html).  While on dev mode, it goes to EDITOR, refer to the function getEditorByType.  Which mode do you use? If dev, then try production.

**Comment by mheicke** [comment]
running it on production mode did work, but now I get another error in 
` CKEDITOR.on("log", function(a) {
        if (window.console && window.console.log) {`

Uncaught TypeError: CKEDITOR.on is not a function

**Comment by eroself** [comment]
Right, that will be fixed in the next release. Cheers.

**Comment by mheicke** [comment]
Ah, cool. Do you have any idea how we can fix it for develop?

**Comment by eroself** [comment]
Use the version 1.0.6, and see if it works?

**Comment by mheicke** [comment]
Okay, I tried 1.0.6, sadly still the same to problems:

- in normal mode it doesn't work because of CKEDITOR.ClassicEditor being undefined and
- in production mode there's an Uncaught TypeError `CKEDITOR.on is not a function`

I cleaned maven, deleted my cache etc

**Comment by eroself** [comment]
It's weird, can you see the [demo](https://www.wontlost.com/ckeditor)?

**Comment by mheicke** [comment]
Hey, sorry for not getting back to you - I had my mind somewhere else and it wondered of. I just saw that Version 2.0.0 of your port came out and wanted to give it another try. First things first: under production mode it works now smoothly. Only problem: I still get a this exception:
```
Uncaught (in promise) TypeError: this.getEditorByType(...) is undefined
    createEditor vaadin-ckeditor.js:148
    firstUpdated vaadin-ckeditor.js:112
    performUpdate updating-element.js:571
    _enqueueUpdate updating-element.js:507
    requestUpdateInternal updating-element.js:473
    initialize updating-element.js:325
    initialize lit-element.js:149
    UpdatingElement updating-element.js:89
    LitElement lit-element.js:81
    VaadinCKEditor vaadin-ckeditor.js:8
```

which results from this code:
```
createEditor() {
        this.getEditorByType(this.editorType).create(document.querySelector( "#"+this.editorId ) , this.getConfig()).then( editor => {
            editor.id = this.editorId;
[...]
```

which calls this line ` return 'classic'===editorType?CKEDITOR.ClassicEditor:` of code from:
```
getEditorByType(editorType) {
        if(typeof CKEDITOR !== 'undefined' && CKEDITOR !== null) {
            return 'classic'===editorType?CKEDITOR.ClassicEditor:
                   'inline'===editorType?CKEDITOR.InlineEditor:
                   'balloon'===editorType?CKEDITOR.BalloonEditor:
                   'decoupled'===editorType?CKEDITOR.DcoupledEditor:
                   _ckeditor__WEBPACK_IMPORTED_MODULE_2__["ClassicEditor"];
        } else {
            return 'classic'===editorType?_ckeditor__WEBPACK_IMPORTED_MODULE_2__["ClassicEditor"]:
                   'inline'===editorType?_ckeditor__WEBPACK_IMPORTED_MODULE_2__["InlineEditor"]:
                   'balloon'===editorType?_ckeditor__WEBPACK_IMPORTED_MODULE_2__["BalloonEditor"]:
                   'decoupled'===editorType?_ckeditor__WEBPACK_IMPORTED_MODULE_2__["DcoupledEditor"]:
                   _ckeditor__WEBPACK_IMPORTED_MODULE_2__["ClassicEditor"];
        }

    }
```
where `CKEDITOR.ClassicEditor` is undefined. I checked the CKEDITOR variable via console and it does not contain a property 'ClassicEditor'
