### ISSUE TITLE
Turkish locale problem

### ISSUE THREAD

**Issue by tJeyhun** [eroself/vaadin-litelement-ckeditor#2]
CKEditor does not work under turkish locale.  Specifically, `CLASSIC & INLINE` types. The problem can be reproduced with `-Duser.language=tr` vmarg. The root of the problem lays in `com.wontlost.ckeditor.EditorType.toString()`. `toLowerCase()' without locale can be very problematic under Turkish locale, even with ANSI strings. I advise the use of toLowerCase(Locale.ENGLISH)

**Comment by eroself** [comment]
Thanks for your advice.
I will apply this on version 1.0.5

**Comment by eroself** [comment]
Applied to version 1.0.5, hoping it fixes your problem
