### ISSUE TITLE
Problems with Binder

### ISSUE THREAD

**Issue by kai83** [eroself/vaadin-litelement-ckeditor#5]
Binder is not showing any error message indicator in the UI if validations fails.
setRequiredIndicatorVisible(true) and setLabel("test") has been set and Binder validation itself works, 
but the UI is not showing an indicator that validation fails.

Also binder.readBean(null); should clear the fields and I guess, it calls setValue.
But as setValue requires updateValue for the ckeditor which might be the reason why binder might fail to clear the fields.

**Comment by eroself** [comment]
Thanks for your findings. I will take a look on this.

**Comment by kai83** [comment]
Thank you. Let me know if you need anything to test.

**Comment by eroself** [comment]
Try the version 1.0.5
