### ISSUE TITLE
Integration with binder not working

### ISSUE THREAD

**Issue by kamuffe** [eroself/vaadin-litelement-ckeditor#7]
Hi.

I tried out CKEditor and want to bind a property from a bean but it is not working.

```
	VaadinCKEditor editor = new VaadinCKEditorBuilder().with( builder ->
	{
		builder.editorType = EditorType.CLASSIC;
		builder.theme = ThemeType.DARK;
		builder.toolbar = builder.toolbar = new Toolbar[] { Toolbar.fontFamily, Toolbar.fontSize, Toolbar.fontColor };
	} ).createVaadinCKEditor();
	binder.forField( editor ).bind( Task::getDescription, Task::setDescription );
	binder.readBean( task );
```
Result is that the text content stored in the tasks description is not shown in the editor UI. Is there something I missed?
Using the same code with a textfield or textarea works and the contents are shown in the fields.

Thanks a lot
Kamuffe

**Comment by kamuffe** [comment]
Hi.

I tested a bit around.

Reading the task does not work or the editor gets not updated with the value. 
On the other hand when writing some data to the editor and calling binder.writeBeanIfValid( task ); will update the task and binding functionallity can be used as usual.

So the only thing which won't work is update the editor ui when calling setBean or readBean on binder.

Best,
Kamuffe

**Comment by eroself** [comment]
Add `builder.editorData = task.getDescription();`  and `binder.setBean(task);` before `binder.readBean( task );`
